# Site settings
title: ProbLang v2
description: "Computational Models of Pragmatic Reasoning"
baseurl: "/probLang-memo" # the subpath of your site, e.g. /blog
url: "https://hawkrobe.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Kramdown settings for math support
kramdown:
  math_engine: katex

# Collections
collections:
  chapters:
    output: true
    permalink: /chapters/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
